name: CI/CD - Build and Deploy Hello App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: julianaaml/hello-app:${{ github.sha }}

      - name: Set image tag output
        id: set_image_tag
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  update-manifests:
    name: Update Image in Manifest Repo
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}

    steps:
      - name: Checkout manifests repo via PAT
        uses: actions/checkout@v4
        with:
          repository: JuhLima89/hello-manifests-pb25
          token: ${{ secrets.GH_PAT_MANIFEST }}
          path: manifests

      - name: Mostrar imagem ANTES do sed (debug)
        run: |
          cd manifests
          echo "ANTES DO SED:"
          grep 'image:' deployment.yaml || echo "Imagem não encontrada."

      - name: Substituir REPLACE_IMAGE_TAG pela nova tag
        run: |
          cd manifests
          sed -i "s|REPLACE_IMAGE_TAG|${IMAGE_TAG}|" deployment.yaml

      - name: Mostrar imagem DEPOIS do sed (debug)
        run: |
          cd manifests
          echo "DEPOIS DO SED:"
          grep 'image:' deployment.yaml || echo "Imagem não encontrada."

      - name: Verificar alterações no git antes do commit (debug)
        run: |
          cd manifests
          git status
          git diff

      - name: Commit e push das mudanças
        working-directory: manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH=update-image-$(date +%s)
          git switch -c $BRANCH

          git add deployment.yaml

          if git diff --cached --quiet; then
            echo "Nada para commitar. Encerrando sem criar PR."
            exit 0
          fi

          git commit -m "Update image to $IMAGE_TAG"
          git push origin $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Criar Pull Request
        if: env.BRANCH != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT_MANIFEST }}
          commit-message: Update image to $IMAGE_TAG
          title: Update image to $IMAGE_TAG
          body: Atualiza a imagem do hello-app com a tag `${{ env.IMAGE_TAG }}`
          base: main
          branch: ${{ env.BRANCH }}
          path: manifests
